spring:
    profiles:
        active: pro

---
spring:
    profiles: pro
    application:
        name: microservicecloud-pro
        
---
spring:
    profiles: test
    application:
        name: microservicecloud-test